# Generated by Django 3.1 on 2023-02-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20230210_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='shrt_desc',
            field=models.TextField(blank=True),
        ),
    ]
