# Generated by Django 3.1 on 2023-02-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_package_shrt_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
