# Generated by Django 3.1 on 2023-02-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.AddField(
            model_name='package',
            name='images',
            field=models.ManyToManyField(blank=True, to='tours.PackageImage'),
        ),
    ]
