# Generated by Django 3.1 on 2023-02-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20230211_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='images',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, upload_to='tours/photos'),
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
    ]
