# Generated by Django 4.2 on 2023-04-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0007_auto_20230211_1933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
